# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
    - 2.7
    - 3.5
    - 3.6

before_install:
  # Additional info about the build
  - uname -a
  - free -m
  - df -h
  - ulimit -a

  # Setup python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Create test environment for package
  - conda create -q -n dqm_env python=$PYTHON_VER numpy nomkl pandas pytables numexpr
  - source activate dqm_env

    # Install anything not in conda
  - pip install pint
  - pip install pytst pytest-cov codecov

    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --yes --use-local project_name

before_script:

    # List out the packages
  - conda list

script:
  - py.test -v --cov=eex/ --durations=5

notifications:
  email: false

after_success:
  - codecov

