environment:

  matrix:

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Try to update conda first to avoid odd dependency clashes
  - conda update --yes --all
  - conda install --yes conda-build

  - conda create --yes -n eex_env numpy pandas pytables numexpr scipy
  - activate eex_env

    # Install anything not in conda
  - pip install pint
  - pip install pytest pytest-cov codecov
  - pip install nbval
  - conda list

    # Install the package locally
  - pip install -e .

build: false

test_script:
  - py.test -v --cov=eex/ --durations=5 --nbval-lax --current-env
