skip_tags: true
clone_depth: 1

environment:

  matrix:

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:
  - conda create -q -n eex_env numpy nomkl pandas pytables numexpr
  - activate eex_env

    # Install anything not in conda
  - pip install pint
  - pip install pytest pytest-cov codecov
  - conda list

    # Install the package locally
  - pip install -e .

build: false

test_script:
  - py.test -v --cov=eex/ --durations=5
